// Code generated by go generate; DO NOT EDIT.

package proto

const (
	EasyTierCommit = "b0176b38f876327cdeea5ccf990bd5485d07ff62"
	SchemaSHA256   = "3eecbde08ff579de2d2420bb995715ce0a32b650fc566b3e5b8280c6f63fa18b"
)
