// Code generated by go generate; DO NOT EDIT.

package proto

const (
	EasyTierCommit = "48aab51c8373a647375809bd82359b94750fbf0d"
	SchemaSHA256   = "6880723c4a0e9dbac256cafa3a557610dcda526db070c533a58067686a57d99d"
)
