// Code generated by go generate; DO NOT EDIT.

package artifact

const (
	Commit = "be0d34cd39af24997a79727218bdd62346d27d01"
	SHA256 = "a6a40bbfcfd69887edf1b9b15d288f6094b8f835963a1000eab7e656c973d404"
)
