// Code generated by go generate; DO NOT EDIT.

package artifact

const (
	Commit = "48aab51c8373a647375809bd82359b94750fbf0d"
	SHA256 = "47d630a900a4b8e6b4a698912a8b02c956eeebafa71d2a861f3516321fd2256d"
)
